#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="$PROJECT_DIR/scripts"
TARGET="esp32s3"
BAUD="${BAUD:-460800}"
PORT="${PORT:-}"
MONITOR=0
FLASH_SPIFFS=0
SPIFFS_ONLY=0
ONION_SHARED_SECRET="${ONION_SHARED_SECRET:-02eb3d5e04fd2dc9cbb6f3f5c6c9d89d9c96acd987cc24ddf9f717f9480e8786}"
ONION_WIFI_SSID="${ONION_WIFI_SSID:-CIC Guest}"
ONION_WIFI_PASSWORD="${ONION_WIFI_PASSWORD:-1nnovation}"
ONION_SERVER_BASE_URL="${ONION_SERVER_BASE_URL:-https://oniondao.dev}"
ONION_BADGE_API_KEY="${ONION_BADGE_API_KEY:-${BADGE_API_KEY:-$ONION_SHARED_SECRET}}"
ONION_MQTT_URI="${ONION_MQTT_URI:-mqtt://shortline.proxy.rlwy.net:20928}"
ONION_MQTT_USERNAME="${ONION_MQTT_USERNAME:-oniondao}"
ONION_MQTT_PASSWORD="${ONION_MQTT_PASSWORD:-$ONION_SHARED_SECRET}"
ONION_MQTT_TOPIC_PREFIX="${ONION_MQTT_TOPIC_PREFIX:-oniondao}"
ONION_SCRIPT_MANIFEST_URL="${ONION_SCRIPT_MANIFEST_URL:-}"

usage() {
  cat <<'EOF'
Usage: scripts/build-flash.sh [options]

Build Onion OS and flash it to the first available ESP32-S3 serial board.
This performs an app update only. It does not erase flash, preserving NVS data
such as the wrapped Solana wallet seed.

Options:
  -p, --port PORT    Flash a specific serial port instead of auto-detecting
  -b, --baud BAUD    Flash baud rate (default: 460800, or $BAUD)
  --spiffs           Also build and flash the SPIFFS partition with scripts/*.lua
  --spiffs-only      Flash only the SPIFFS partition (skip app build/flash)
  --monitor          Open idf.py monitor after flashing
  -h, --help         Show this help

Environment:
  IDF_EXPORT=/path/to/export.sh  ESP-IDF export script to source
  PORT=/dev/cu.usbserial-10      Same as --port
  BAUD=921600                    Same as --baud
  ONION_WIFI_SSID="CIC Guest"    Baked WiFi SSID
  ONION_WIFI_PASSWORD=1nnovation Baked WiFi password
  BADGE_API_KEY=...              Baked badge API key / check-in secret
  ONION_SHARED_SECRET=...        Default for BADGE_API_KEY and MQTT password
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p|--port)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 2; }
      PORT="$2"
      shift 2
      ;;
    -b|--baud)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 2; }
      BAUD="$2"
      shift 2
      ;;
    --erase)
      echo "Refusing to erase flash: Onion OS stores the wrapped Solana wallet seed in NVS." >&2
      echo "Use idf.py erase-flash manually only when you intentionally want to delete badge state." >&2
      exit 2
      ;;
    --spiffs)
      FLASH_SPIFFS=1
      shift
      ;;
    --spiffs-only)
      FLASH_SPIFFS=1
      SPIFFS_ONLY=1
      shift
      ;;
    --monitor)
      MONITOR=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    echo "Install ESP-IDF or pass IDF_EXPORT=/path/to/esp-idf/export.sh" >&2
    exit 1
  fi
}

source_esp_idf() {
  command -v idf.py >/dev/null 2>&1 && return 0

  local candidates=()
  if [[ -n "${IDF_EXPORT:-}" ]]; then
    candidates+=("$IDF_EXPORT")
  fi

  candidates+=(
    "$HOME/.espressif/v5.5.4/esp-idf/export.sh"
    "$HOME/.espressif-5.5.4/v5.5.4/esp-idf/export.sh"
    "$HOME/esp/esp-idf/export.sh"
    "$HOME"/.espressif/v5.5.*/esp-idf/export.sh
    "$HOME"/.espressif-5.5.*/v5.5.*/esp-idf/export.sh
    "$HOME/.platformio/packages/framework-espidf/export.sh"
  )

  local export_script
  local export_log="${TMPDIR:-/tmp}/onion-os-idf-export.log"
  for export_script in "${candidates[@]}"; do
    if [[ -f "$export_script" ]]; then
      echo "Loading ESP-IDF from $export_script"
      # shellcheck disable=SC1090
      if . "$export_script" >"$export_log" 2>&1; then
        command -v idf.py >/dev/null 2>&1 && return 0
      else
        echo "Failed to load ESP-IDF from $export_script" >&2
        tail -n 40 "$export_log" >&2 || true
      fi
    fi
  done

  return 1
}

esptool_command() {
  if command -v esptool.py >/dev/null 2>&1; then
    echo "esptool.py"
  elif command -v esptool >/dev/null 2>&1; then
    echo "esptool"
  else
    echo ""
  fi
}

# esptool v5+ uses hyphenated subcommands (write-flash, chip-id), older
# versions use underscores (write_flash, chip_id).  Detect once so every
# call site can use the right form.
detect_esptool_subcmd_style() {
  local help
  help="$("$ESPTOOL" --help 2>&1 || true)"
  if echo "$help" | grep -q 'chip-id'; then
    ESP_CHIP_ID="chip-id"
    ESP_WRITE_FLASH="write-flash"
  else
    ESP_CHIP_ID="chip_id"
    ESP_WRITE_FLASH="write_flash"
  fi
}

c_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

write_generated_config() {
  local config_path="$PROJECT_DIR/main/onion_config.generated.h"

  {
    printf '#pragma once\n\n'
    printf '// Generated by scripts/build-flash.sh. Do not commit.\n\n'
    printf '#define ONION_DEFAULT_WIFI_SSID %s\n' "$(c_string "$ONION_WIFI_SSID")"
    printf '#define ONION_DEFAULT_WIFI_PASSWORD %s\n' "$(c_string "$ONION_WIFI_PASSWORD")"
    printf '#define ONION_DEFAULT_SERVER_BASE_URL %s\n' "$(c_string "$ONION_SERVER_BASE_URL")"
    printf '#define ONION_DEFAULT_BADGE_API_KEY %s\n' "$(c_string "$ONION_BADGE_API_KEY")"
    printf '#define ONION_DEFAULT_MQTT_URI %s\n' "$(c_string "$ONION_MQTT_URI")"
    printf '#define ONION_DEFAULT_MQTT_USERNAME %s\n' "$(c_string "$ONION_MQTT_USERNAME")"
    printf '#define ONION_DEFAULT_MQTT_PASSWORD %s\n' "$(c_string "$ONION_MQTT_PASSWORD")"
    printf '#define ONION_DEFAULT_MQTT_TOPIC_PREFIX %s\n' "$(c_string "$ONION_MQTT_TOPIC_PREFIX")"
    printf '#define ONION_DEFAULT_SCRIPT_MANIFEST_URL %s\n\n' "$(c_string "$ONION_SCRIPT_MANIFEST_URL")"
    printf '#define ONION_HARDCODED_WIFI_SSID %s\n' "$(c_string "$ONION_WIFI_SSID")"
    printf '#define ONION_HARDCODED_WIFI_PASSWORD %s\n' "$(c_string "$ONION_WIFI_PASSWORD")"
    printf '#define ONION_HARDCODED_SERVER_BASE_URL %s\n' "$(c_string "$ONION_SERVER_BASE_URL")"
    printf '#define ONION_HARDCODED_MQTT_URI %s\n' "$(c_string "$ONION_MQTT_URI")"
    printf '#define ONION_HARDCODED_MQTT_USERNAME %s\n' "$(c_string "$ONION_MQTT_USERNAME")"
    printf '#define ONION_HARDCODED_MQTT_PASSWORD %s\n' "$(c_string "$ONION_MQTT_PASSWORD")"
  } >"$config_path"

  echo "Wrote script-managed config: main/onion_config.generated.h"
}

candidate_ports() {
  local patterns=(
    "/dev/cu.usbserial"* "/dev/tty.usbserial"*
    "/dev/cu.usbmodem"* "/dev/tty.usbmodem"*
    "/dev/cu.wchusbserial"* "/dev/tty.wchusbserial"*
    "/dev/cu.SLAB_USBtoUART"* "/dev/tty.SLAB_USBtoUART"*
    "/dev/ttyUSB"* "/dev/ttyACM"*
  )
  local port
  for port in "${patterns[@]}"; do
    [[ -e "$port" ]] && printf '%s\n' "$port"
  done | sort -u
}

probe_esp32s3_port() {
  local port="$1"
  local output

  if ! output="$("$ESPTOOL" --chip auto --port "$port" "$ESP_CHIP_ID" 2>&1)"; then
    return 1
  fi

  grep -Eiq 'ESP32-S3|ESP32S3|esp32s3' <<<"$output"
}

detect_port() {
  local port
  while IFS= read -r port; do
    echo "Probing $port..." >&2
    if probe_esp32s3_port "$port"; then
      printf '%s\n' "$port"
      return 0
    fi
  done < <(candidate_ports)

  return 1
}

source_esp_idf || true
require_command idf.py
ESPTOOL="$(esptool_command)"
if [[ -z "$ESPTOOL" ]]; then
  echo "Required command not found: esptool.py or esptool" >&2
  echo "Install ESP-IDF or pass IDF_EXPORT=/path/to/esp-idf/export.sh" >&2
  exit 1
fi
detect_esptool_subcmd_style

cd "$PROJECT_DIR"
write_generated_config

if [[ -z "$PORT" ]]; then
  echo "Searching for the first available ESP32-S3 serial board..."
  if ! PORT="$(detect_port)"; then
    echo "No ESP32-S3 board found on common serial ports." >&2
    echo "Connect the badge, or pass a port explicitly with --port /dev/..." >&2
    exit 1
  fi
else
  if [[ ! -e "$PORT" ]]; then
    echo "Serial port does not exist: $PORT" >&2
    exit 1
  fi
  if ! probe_esp32s3_port "$PORT"; then
    echo "Port exists but did not respond as an ESP32-S3: $PORT" >&2
    exit 1
  fi
fi

echo "Using ESP32-S3 on $PORT"

# --- SPIFFS helpers -----------------------------------------------------------

# spiffs offset and size value defined in partition.csv
SPIFFS_PART_OFFSET=0x670000
SPIFFS_PART_SIZE=0x180000   # 1.5 MB

build_spiffs_image() {
  local staging
  staging="$(mktemp -d)"
  trap 'rm -rf "$staging"' EXIT

  # Copy .lua files from scripts/ into the staging dir with the /scripts_
  # prefix the firmware expects (see lua_api.cpp runScriptByName).
  local count=0
  for f in "$SCRIPTS_DIR"/*.lua; do
    [[ -f "$f" ]] || continue
    cp "$f" "$staging/scripts_$(basename "$f")"
    count=$((count + 1))
  done

  if [[ $count -eq 0 ]]; then
    echo "No .lua files in $SCRIPTS_DIR" >&2
    return 1
  fi

  echo "Building SPIFFS image from $count script(s)..."

  # spiffsgen.py lives inside the ESP-IDF tree
  local spiffsgen="$IDF_PATH/components/spiffs/spiffsgen.py"
  if [[ ! -f "$spiffsgen" ]]; then
    echo "Cannot find spiffsgen.py — set IDF_PATH or install ESP-IDF" >&2
    return 1
  fi

  SPIFFS_BIN="$PROJECT_DIR/build/spiffs.bin"
  python "$spiffsgen" "$SPIFFS_PART_SIZE" "$staging" "$SPIFFS_BIN"
  echo "SPIFFS image: $SPIFFS_BIN"
}

flash_spiffs_image() {
  if [[ ! -f "$SPIFFS_BIN" ]]; then
    echo "SPIFFS image not found at $SPIFFS_BIN" >&2
    return 1
  fi
  echo "Flashing SPIFFS at $SPIFFS_PART_OFFSET..."
  "$ESPTOOL" -p "$PORT" -b "$BAUD" --chip esp32s3 \
    "$ESP_WRITE_FLASH" "$SPIFFS_PART_OFFSET" "$SPIFFS_BIN"
}

# --- Build & flash ------------------------------------------------------------

if [[ ! -f sdkconfig ]] || ! grep -q '^CONFIG_IDF_TARGET="esp32s3"$' sdkconfig; then
  idf.py set-target "$TARGET"
fi

if [[ "$SPIFFS_ONLY" -eq 0 ]]; then
  idf.py build
  if [[ "$MONITOR" -eq 1 ]]; then
    idf.py -p "$PORT" -b "$BAUD" flash monitor
  else
    idf.py -p "$PORT" -b "$BAUD" flash
  fi
fi

if [[ "$FLASH_SPIFFS" -eq 1 ]]; then
  build_spiffs_image
  flash_spiffs_image
  if [[ "$MONITOR" -eq 1 ]]; then
    idf.py -p "$PORT" -b "$BAUD" monitor
  fi
fi
